spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: qingcaini
  jpa:
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true